# Generated by Django 6.0.1 on 2026-03-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='promo_video',
            field=models.FileField(blank=True, null=True, upload_to='subcategories/videos/', verbose_name='Промо видео'),
        ),
    ]
